# Generated by Django 5.0 on 2024-06-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
